---
Parameters:
  HttpSecurityGroupDescription:
    Description: Enter description for this Http security group
    Type: String

Mappings:
  RegionMap:
    eu-north-1:
      "linux64": "ami-0c5254b956817b326"
      "AZ": "eu-north-1a"
      "instanceType": "t3.micro"


Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !FindInMap [RegionMap, !Ref "AWS::Region", "AZ"]
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", "linux64"]
      InstanceType: !FindInMap [RegionMap, !Ref "AWS::Region", "instanceType"]
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref HTTPSecurityGroup

  # Elastic IP for the instance
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyInstance

  # EC2 Security Group
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html#cfn-ec2-securitygroup-groupdescription
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: EC2SSH
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22

  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: EC2HTTPGroup
      GroupDescription: !Ref HttpSecurityGroupDescription
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80

