---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template EC2InstanceWithSecurityGroupSample:
  Create an Amazon EC2 instance running the Amazon Linux AMI. The AMI is chosen based
  on the region in which the stack is run. This example creates an EC2 security group
  for the instance to give you SSH access. **WARNING** This template creates an Amazon
  EC2 instance. You will be billed for the AWS resources used if you create a stack
  from this template.'

Parameters:
  HttpSecurityGroupDescription:
    Description: Description for this Http security group
    Type: String
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Mappings:
  RegionMap:
    eu-north-1:
      "linux64": "ami-0c5254b956817b326"
      "AZ": "eu-north-1a"
      "instanceType": "t3.micro"

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !FindInMap [RegionMap, !Ref "AWS::Region", "AZ"]
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", "linux64"]
      InstanceType: !FindInMap [RegionMap, !Ref "AWS::Region", "instanceType"]
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref HTTPSecurityGroup

  SSHSecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://cf-ssh-security-stack.s3.eu-north-1.amazonaws.com/ssh-security-group.yaml"

  # Elastic IP for the instance
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyInstance

  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: EC2CFHTTPGroup
      GroupDescription: !Ref HttpSecurityGroupDescription
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80

